version: '3.4'

services:
  clientwebmvc:
    image: gorbatukam/example-web-deploy:latest
    build:
      context: ./Client.WebMvc
      dockerfile: Dockerfile
    expose:
      - "8080"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Подключаем конфигурацию Nginx
    depends_on:
      - clientwebmvc